// Custom Expo config plugin: disable Xcode's User Script Sandboxing.
//
// Expo SDK 55 prebuild sets ENABLE_USER_SCRIPT_SANDBOXING = YES, which blocks
// CocoaPods' "[CP] Copy Pods Resources" script from writing its
// resources-to-copy-*.txt temp file, failing local builds with:
//   Sandbox: bash(...) deny(1) file-write-create .../Pods/resources-to-copy-FitKit.txt
//
// ios/ is gitignored (regenerated by prebuild), so we flip this build setting
// here instead of editing project.pbxproj, keeping the fix durable.
const { withXcodeProject } = require('expo/config-plugins');

const withDisableScriptSandbox = (config) =>
  withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const configurations = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(configurations)) {
      const buildSettings = configurations[key].buildSettings;
      if (buildSettings) {
        buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = 'NO';
      }
    }
    return cfg;
  });

module.exports = withDisableScriptSandbox;
